package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvu generated by hbm2java
 */
@Entity
@Table(name="CHUCVU"
    ,schema="dbo"
    ,catalog="sql"
)
public class Chucvu  implements java.io.Serializable {


     private String maCv;
     private Mucluong mucluong;
     private String tenCv;
     private long baoHiem;
     private long troCap;
     private Set<PhongbanChucvu> phongbanChucvus = new HashSet<PhongbanChucvu>(0);
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

    public Chucvu() {
    }

	
    public Chucvu(String maCv, Mucluong mucluong, String tenCv, long baoHiem, long troCap) {
        this.maCv = maCv;
        this.mucluong = mucluong;
        this.tenCv = tenCv;
        this.baoHiem = baoHiem;
        this.troCap = troCap;
    }
    public Chucvu(String maCv, Mucluong mucluong, String tenCv, long baoHiem, long troCap, Set<PhongbanChucvu> phongbanChucvus, Set<Nhanvien> nhanviens) {
       this.maCv = maCv;
       this.mucluong = mucluong;
       this.tenCv = tenCv;
       this.baoHiem = baoHiem;
       this.troCap = troCap;
       this.phongbanChucvus = phongbanChucvus;
       this.nhanviens = nhanviens;
    }
   
     @Id 

    
    @Column(name="MaCV", unique=true, nullable=false)
    public String getMaCv() {
        return this.maCv;
    }
    
    public void setMaCv(String maCv) {
        this.maCv = maCv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaML", nullable=false)
    public Mucluong getMucluong() {
        return this.mucluong;
    }
    
    public void setMucluong(Mucluong mucluong) {
        this.mucluong = mucluong;
    }

    
    @Column(name="TenCV", nullable=false)
    public String getTenCv() {
        return this.tenCv;
    }
    
    public void setTenCv(String tenCv) {
        this.tenCv = tenCv;
    }

    
    @Column(name="BaoHiem", nullable=false, precision=18, scale=0)
    public long getBaoHiem() {
        return this.baoHiem;
    }
    
    public void setBaoHiem(long baoHiem) {
        this.baoHiem = baoHiem;
    }

    
    @Column(name="TroCap", nullable=false, precision=18, scale=0)
    public long getTroCap() {
        return this.troCap;
    }
    
    public void setTroCap(long troCap) {
        this.troCap = troCap;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chucvu")
    public Set<PhongbanChucvu> getPhongbanChucvus() {
        return this.phongbanChucvus;
    }
    
    public void setPhongbanChucvus(Set<PhongbanChucvu> phongbanChucvus) {
        this.phongbanChucvus = phongbanChucvus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chucvu")
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }




}


