package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChuyenmonTrinhdohv generated by hbm2java
 */
@Entity
@Table(name="CHUYENMON_TRINHDOHV"
    ,schema="dbo"
    ,catalog="sql"
)
public class ChuyenmonTrinhdohv  implements java.io.Serializable {


     private String maCm;
     private String maTdhv;

    public ChuyenmonTrinhdohv() {
    }

    public ChuyenmonTrinhdohv(String maCm, String maTdhv) {
       this.maCm = maCm;
       this.maTdhv = maTdhv;
    }
   
     @Id 

    
    @Column(name="MaCM", unique=true, nullable=false)
    public String getMaCm() {
        return this.maCm;
    }
    
    public void setMaCm(String maCm) {
        this.maCm = maCm;
    }

    
    @Column(name="MaTDHV", nullable=false)
    public String getMaTdhv() {
        return this.maTdhv;
    }
    
    public void setMaTdhv(String maTdhv) {
        this.maTdhv = maTdhv;
    }




}


