package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chuyenmon generated by hbm2java
 */
@Entity
@Table(name="CHUYENMON"
    ,schema="dbo"
    ,catalog="sql"
)
public class Chuyenmon  implements java.io.Serializable {


     private String maCm;
     private String tenCm;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

    public Chuyenmon() {
    }

	
    public Chuyenmon(String maCm, String tenCm) {
        this.maCm = maCm;
        this.tenCm = tenCm;
    }
    public Chuyenmon(String maCm, String tenCm, Set<Nhanvien> nhanviens) {
       this.maCm = maCm;
       this.tenCm = tenCm;
       this.nhanviens = nhanviens;
    }
   
     @Id 

    
    @Column(name="MaCM", unique=true, nullable=false)
    public String getMaCm() {
        return this.maCm;
    }
    
    public void setMaCm(String maCm) {
        this.maCm = maCm;
    }

    
    @Column(name="TenCM", nullable=false)
    public String getTenCm() {
        return this.tenCm;
    }
    
    public void setTenCm(String tenCm) {
        this.tenCm = tenCm;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chuyenmon")
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }




}


