package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Ktkl generated by hbm2java
 */
@Entity
@Table(name="KTKL"
    ,schema="dbo"
    ,catalog="sql"
)
public class Ktkl  implements java.io.Serializable {


     private String maKtkl;
     private KtklNhanvien ktklNhanvien;
     private String tenKtkl;
     private String hinhThuc;
     private String soTien;

    public Ktkl() {
    }

    public Ktkl(KtklNhanvien ktklNhanvien, String tenKtkl, String hinhThuc, String soTien) {
       this.ktklNhanvien = ktklNhanvien;
       this.tenKtkl = tenKtkl;
       this.hinhThuc = hinhThuc;
       this.soTien = soTien;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="ktklNhanvien"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="MaKTKL", unique=true, nullable=false)
    public String getMaKtkl() {
        return this.maKtkl;
    }
    
    public void setMaKtkl(String maKtkl) {
        this.maKtkl = maKtkl;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public KtklNhanvien getKtklNhanvien() {
        return this.ktklNhanvien;
    }
    
    public void setKtklNhanvien(KtklNhanvien ktklNhanvien) {
        this.ktklNhanvien = ktklNhanvien;
    }

    
    @Column(name="TenKTKL", nullable=false)
    public String getTenKtkl() {
        return this.tenKtkl;
    }
    
    public void setTenKtkl(String tenKtkl) {
        this.tenKtkl = tenKtkl;
    }

    
    @Column(name="HinhThuc", nullable=false)
    public String getHinhThuc() {
        return this.hinhThuc;
    }
    
    public void setHinhThuc(String hinhThuc) {
        this.hinhThuc = hinhThuc;
    }

    
    @Column(name="SoTien", nullable=false)
    public String getSoTien() {
        return this.soTien;
    }
    
    public void setSoTien(String soTien) {
        this.soTien = soTien;
    }




}


