package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lilichct generated by hbm2java
 */
@Entity
@Table(name="LILICHCT"
    ,schema="dbo"
    ,catalog="sql"
)
public class Lilichct  implements java.io.Serializable {


     private String maNoiCt;
     private String tenNoiCt;
     private String dc;
     private Set<NhanvienLilichct> nhanvienLilichcts = new HashSet<NhanvienLilichct>(0);

    public Lilichct() {
    }

	
    public Lilichct(String maNoiCt, String tenNoiCt, String dc) {
        this.maNoiCt = maNoiCt;
        this.tenNoiCt = tenNoiCt;
        this.dc = dc;
    }
    public Lilichct(String maNoiCt, String tenNoiCt, String dc, Set<NhanvienLilichct> nhanvienLilichcts) {
       this.maNoiCt = maNoiCt;
       this.tenNoiCt = tenNoiCt;
       this.dc = dc;
       this.nhanvienLilichcts = nhanvienLilichcts;
    }
   
     @Id 

    
    @Column(name="MaNoiCT", unique=true, nullable=false)
    public String getMaNoiCt() {
        return this.maNoiCt;
    }
    
    public void setMaNoiCt(String maNoiCt) {
        this.maNoiCt = maNoiCt;
    }

    
    @Column(name="TenNoiCT", nullable=false)
    public String getTenNoiCt() {
        return this.tenNoiCt;
    }
    
    public void setTenNoiCt(String tenNoiCt) {
        this.tenNoiCt = tenNoiCt;
    }

    
    @Column(name="DC", nullable=false)
    public String getDc() {
        return this.dc;
    }
    
    public void setDc(String dc) {
        this.dc = dc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lilichct")
    public Set<NhanvienLilichct> getNhanvienLilichcts() {
        return this.nhanvienLilichcts;
    }
    
    public void setNhanvienLilichcts(Set<NhanvienLilichct> nhanvienLilichcts) {
        this.nhanvienLilichcts = nhanvienLilichcts;
    }




}


