package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mucluong generated by hbm2java
 */
@Entity
@Table(name="MUCLUONG"
    ,schema="dbo"
    ,catalog="sql"
)
public class Mucluong  implements java.io.Serializable {


     private String maMl;
     private long soTien;
     private Set<Chucvu> chucvus = new HashSet<Chucvu>(0);

    public Mucluong() {
    }

	
    public Mucluong(String maMl, long soTien) {
        this.maMl = maMl;
        this.soTien = soTien;
    }
    public Mucluong(String maMl, long soTien, Set<Chucvu> chucvus) {
       this.maMl = maMl;
       this.soTien = soTien;
       this.chucvus = chucvus;
    }
   
     @Id


    @Column(name="MaML", unique=true, nullable=false)
    public String getMaMl() {
        return this.maMl;
    }
    
    public void setMaMl(String maMl) {
        this.maMl = maMl;
    }

    
    @Column(name="SoTien", nullable=false, precision=18, scale=0)
    public long getSoTien() {
        return this.soTien;
    }
    
    public void setSoTien(long soTien) {
        this.soTien = soTien;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mucluong")
    public Set<Chucvu> getChucvus() {
        return this.chucvus;
    }
    
    public void setChucvus(Set<Chucvu> chucvus) {
        this.chucvus = chucvus;
    }




}


