package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * NhanvienLilichct generated by hbm2java
 */
@Entity
@Table(name="NHANVIEN_LILICHCT"
    ,schema="dbo"
    ,catalog="sql"
)
public class NhanvienLilichct  implements java.io.Serializable {


     private String maNv;
     private Lilichct lilichct;
     private Nhanvien nhanvien;
     private Date thGian;

    public NhanvienLilichct() {
    }

    public NhanvienLilichct(Lilichct lilichct, Nhanvien nhanvien, Date thGian) {
       this.lilichct = lilichct;
       this.nhanvien = nhanvien;
       this.thGian = thGian;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="nhanvien"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="MaNV", unique=true, nullable=false)
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaNoiCT", nullable=false)
    public Lilichct getLilichct() {
        return this.lilichct;
    }
    
    public void setLilichct(Lilichct lilichct) {
        this.lilichct = lilichct;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ThGian", nullable=false, length=23)
    public Date getThGian() {
        return this.thGian;
    }
    
    public void setThGian(Date thGian) {
        this.thGian = thGian;
    }




}


