package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phieuluong generated by hbm2java
 */
@Entity
@Table(name="PHIEULUONG"
    ,schema="dbo"
    ,catalog="sql"
)
public class Phieuluong  implements java.io.Serializable {


     private String maPl;
     private Nhanvien nhanvien;
     private long tongSoTien;
     private Date ngayPhat;

    public Phieuluong() {
    }

    public Phieuluong(String maPl, Nhanvien nhanvien, long tongSoTien, Date ngayPhat) {
       this.maPl = maPl;
       this.nhanvien = nhanvien;
       this.tongSoTien = tongSoTien;
       this.ngayPhat = ngayPhat;
    }
   
     @Id 

    
    @Column(name="MaPL", unique=true, nullable=false)
    public String getMaPl() {
        return this.maPl;
    }
    
    public void setMaPl(String maPl) {
        this.maPl = maPl;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaNv", nullable=false)
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

    
    @Column(name="TongSoTien", nullable=false, precision=18, scale=0)
    public long getTongSoTien() {
        return this.tongSoTien;
    }
    
    public void setTongSoTien(long tongSoTien) {
        this.tongSoTien = tongSoTien;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgayPhat", nullable=false, length=23)
    public Date getNgayPhat() {
        return this.ngayPhat;
    }
    
    public void setNgayPhat(Date ngayPhat) {
        this.ngayPhat = ngayPhat;
    }




}


