package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * PhongbanChucvu generated by hbm2java
 */
@Entity
@Table(name="PHONGBAN_CHUCVU"
    ,schema="dbo"
    ,catalog="sql"
)
public class PhongbanChucvu  implements java.io.Serializable {


     private String maPb;
     private Chucvu chucvu;
     private Phongban phongban;

    public PhongbanChucvu() {
    }

	
    public PhongbanChucvu(String maPb, Chucvu chucvu) {
        this.maPb = maPb;
        this.chucvu = chucvu;
    }
    public PhongbanChucvu(String maPb, Chucvu chucvu, Phongban phongban) {
       this.maPb = maPb;
       this.chucvu = chucvu;
       this.phongban = phongban;
    }
   
     @Id 

    
    @Column(name="MaPB", unique=true, nullable=false)
    public String getMaPb() {
        return this.maPb;
    }
    
    public void setMaPb(String maPb) {
        this.maPb = maPb;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaCV", nullable=false)
    public Chucvu getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Chucvu chucvu) {
        this.chucvu = chucvu;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="phongbanChucvu")
    public Phongban getPhongban() {
        return this.phongban;
    }
    
    public void setPhongban(Phongban phongban) {
        this.phongban = phongban;
    }




}


