package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Quequan generated by hbm2java
 */
@Entity
@Table(name="QUEQUAN"
    ,schema="dbo"
    ,catalog="sql"
)
public class Quequan  implements java.io.Serializable {


     private String maT;
     private Huyen huyen;
     private Tinh tinh;

    public Quequan() {
    }

    public Quequan(Huyen huyen, Tinh tinh) {
       this.huyen = huyen;
       this.tinh = tinh;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="tinh"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="MaT", unique=true, nullable=false)
    public String getMaT() {
        return this.maT;
    }
    
    public void setMaT(String maT) {
        this.maT = maT;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaH", nullable=false)
    public Huyen getHuyen() {
        return this.huyen;
    }
    
    public void setHuyen(Huyen huyen) {
        this.huyen = huyen;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Tinh getTinh() {
        return this.tinh;
    }
    
    public void setTinh(Tinh tinh) {
        this.tinh = tinh;
    }




}


