package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Thannhan generated by hbm2java
 */
@Entity
@Table(name="THANNHAN"
    ,schema="dbo"
    ,catalog="sql"
)
public class Thannhan  implements java.io.Serializable {


     private String maNv;
     private String tenTn;
     private boolean phai;
     private String dc;
     private Date ngSinh;
     private String quanHe;
     private Nhanvien nhanvien;

    public Thannhan() {
    }

	
    public Thannhan(String maNv, String tenTn, boolean phai, String dc, Date ngSinh, String quanHe) {
        this.maNv = maNv;
        this.tenTn = tenTn;
        this.phai = phai;
        this.dc = dc;
        this.ngSinh = ngSinh;
        this.quanHe = quanHe;
    }
    public Thannhan(String maNv, String tenTn, boolean phai, String dc, Date ngSinh, String quanHe, Nhanvien nhanvien) {
       this.maNv = maNv;
       this.tenTn = tenTn;
       this.phai = phai;
       this.dc = dc;
       this.ngSinh = ngSinh;
       this.quanHe = quanHe;
       this.nhanvien = nhanvien;
    }
   
     @Id 

    
    @Column(name="MaNV", unique=true, nullable=false)
    public String getMaNv() {
        return this.maNv;
    }
    
    public void setMaNv(String maNv) {
        this.maNv = maNv;
    }

    
    @Column(name="TenTN", nullable=false)
    public String getTenTn() {
        return this.tenTn;
    }
    
    public void setTenTn(String tenTn) {
        this.tenTn = tenTn;
    }

    
    @Column(name="Phai", nullable=false)
    public boolean isPhai() {
        return this.phai;
    }
    
    public void setPhai(boolean phai) {
        this.phai = phai;
    }

    
    @Column(name="DC", nullable=false)
    public String getDc() {
        return this.dc;
    }
    
    public void setDc(String dc) {
        this.dc = dc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NgSinh", nullable=false, length=23)
    public Date getNgSinh() {
        return this.ngSinh;
    }
    
    public void setNgSinh(Date ngSinh) {
        this.ngSinh = ngSinh;
    }

    
    @Column(name="QuanHe", nullable=false)
    public String getQuanHe() {
        return this.quanHe;
    }
    
    public void setQuanHe(String quanHe) {
        this.quanHe = quanHe;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="thannhan")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }




}


