package com.app.model;
// Generated Oct 16, 2018 12:07:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trinhdonn generated by hbm2java
 */
@Entity
@Table(name="TRINHDONN"
    ,schema="dbo"
    ,catalog="sql"
)
public class Trinhdonn  implements java.io.Serializable {


     private String maTdnn;
     private String tenTdnn;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(0);

    public Trinhdonn() {
    }

	
    public Trinhdonn(String maTdnn, String tenTdnn) {
        this.maTdnn = maTdnn;
        this.tenTdnn = tenTdnn;
    }
    public Trinhdonn(String maTdnn, String tenTdnn, Set<Nhanvien> nhanviens) {
       this.maTdnn = maTdnn;
       this.tenTdnn = tenTdnn;
       this.nhanviens = nhanviens;
    }
   
     @Id 

    
    @Column(name="MaTDNN", unique=true, nullable=false)
    public String getMaTdnn() {
        return this.maTdnn;
    }
    
    public void setMaTdnn(String maTdnn) {
        this.maTdnn = maTdnn;
    }

    
    @Column(name="TenTDNN", nullable=false)
    public String getTenTdnn() {
        return this.tenTdnn;
    }
    
    public void setTenTdnn(String tenTdnn) {
        this.tenTdnn = tenTdnn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trinhdonn")
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }




}


